name: Deploy static content to Pages

on:
  push:
    branches:
      - main  
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GH Pages
        uses: anigieous/Deploy-Static-Website-to-GH-PAges/static@main
        with: 
          repo_name: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
      
