name: Deploy static content to Pages

on:
  push:
    branches:
      - main  
  workflow_dispatch:

jobs:
  deploy:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GH Pages
        uses: anigieous/Deploy-Static-Website-to-GH-PAges/static@main
        with: 
          repo_name: ${{ github.repository }}
          token: ${{ secrets.AKASH_TOKEN }}
      
